### ISSUE TITLE
Decorated object only works for first level properties

### ISSUE THREAD

**Issue by hector** [caiogondim/safe-chain.js#1]
```javascript
const obj = {
  a: undefined
}

const decoratedObj = safeChain(obj)

decoratedObj.a === undefined // works
decoratedObj.a.b === undefined // throws error
```

Am I doing something wrong? Looking at the source code it seems like it has to behave like this.

**Comment by caiogondim** [comment]
Just checked and it is indeed behaving like this.
The problem is here https://github.com/caiogondim/safe-chain.js/blob/master/src/index.js#L6

When you do `obj.a` it passes though the Proxy on `obj`.
But when you do `obj.a.b` it doesn't.
```js
obj.a.b

// Equals to

var a = obj.a
var b = a.b
```

We should have to apply a Proxy in every possible property, and in every possible property of every possible property. It's essentially `∞!` (factorial of infinity). 
I'm not sure we can work around this.
An ideas?

**Comment by caiogondim** [comment]
Case we can't work around this, I will remove this "feature" since it's essentially broken.

**Comment by caiogondim** [comment]
I had to remove decorator since there is no hack around this =/

**Comment by hector** [comment]
Sorry for the delay.
I have the impression there is a solution for this. Instead of returning the real property, we always have to return a Proxy. This Proxy will always return another Proxy when accessing its properties.
Do you know how to do it? If not I can try it, but in that case could you give me a few instructions on how to run the tests?

**Comment by caiogondim** [comment]
That would be super helpful to have this fixed 😄 

To run the tests: `npm run test`
They are on the `test/` folder.
Just add your use case there and try to fix it on `src/`

Please, let me know if I can help you out.
